export 'splashScreen/splash_screen.dart';
export 'splashScreen/splash_screen2.dart';
export 'authScreen/auth_screen.dart';
export 'signupScreen/signup_screen.dart';
export 'loginScreen/login_screen.dart';
export 'homeScreen/home_screen.dart';
export 'profileScreen/profile_screen.dart';
export 'sellScreen/sell_screen.dart';
export 'wallpaperScreen/wallpaper_screen.dart';
